name = "tor"
main = "src/index.ts"
compatibility_date = "2026-08-20"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

routes = [
  { pattern = "cherrytor.io.vn", custom_domain = true },
  { pattern = "www.cherrytor.io.vn", custom_domain = true }
]

[vars]
ENVIRONMENT = "production"
MAX_REQUESTS_PER_MIN = "600"
